/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotoMVP } from "./VotoMVP";
export * as factories from "./factories";
export { VotoMVP__factory } from "./factories/VotoMVP__factory";
